# Generated by Django 4.1.7 on 2023-06-06 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0005_article_puplished'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='puplished',
            new_name='published',
        ),
    ]
