# Generated by Django 4.1.7 on 2023-06-08 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0007_rename_articleblock_articlesblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlesblock',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
